version: 2
sources:
  - name: y1990s
    schema: years1990s
    tables:
      - name: tbl_asean_cities
      - name: tbl_daily_data
      - name: tbl_daily_units
      - name: tbl_hourly_data
      - name: tbl_hourly_units